export const API_STATUS = {
    NONE: 0,
    REQUEST: 1,
    SUCCESS: 2,
    FAILURE: 3,
}

export const RETURN_TEXT = {
    RECORD_NOT_FOUND: "RECORD_NOT_FOUND",
    REDIRECT_CREATE_PASSWORD: "REDIRECT_CREATE_PASSWORD",
    PASSWORD_CREATED: "PASSWORD_CREATED",
    PASSWORD_ALREADY_CREATED: "PASSWORD_ALREADY_CREATED",
}

export const INFO_MODAL_STATUS = {
    SUCCESS: 1,
    WARNING: 2,
    FAILURE: 3,
}


